# Generated by Django 4.2.2 on 2023-07-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('mail_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('gst_number', models.CharField(default='None', max_length=100)),
                ('state_code', models.CharField(max_length=100)),
            ],
        ),
    ]
