# Generated by Django 4.2.2 on 2023-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cgst',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='igst',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sgst',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
