# Generated by Django 4.2.3 on 2023-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0006_newinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=100)),
                ('no_of_units_allowed', models.CharField(max_length=100)),
                ('cost_per_unit', models.CharField(max_length=100)),
            ],
        ),
    ]
