# Generated by Django 4.2.3 on 2023-08-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_invoiceproductdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('no_of_units_allowed', models.PositiveIntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='InvoiceProductDetails',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='no_of_units_allowed',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='purchase_id',
        ),
        migrations.AlterField(
            model_name='newinvoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.newinvoice'),
        ),
    ]
