# Generated by Django 4.2.3 on 2023-09-01 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_productdetails_delete_invoiceproductdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
