# Generated by Django 4.2.3 on 2023-09-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0010_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
